chloec222/onTilt

app/public/userdashboard.html

Added a dashboard page for users. Dashboard has three cards; a user card, an upcoming bets card, and a past bets card. I also added a navbar, and we should add our logo into it (in center). Design is built with UIKit web framework (getuikit.com).

User dashboard

---

app/public/css/userdash.css
app/public/userdash.js
app/public/userdashboard.html

Added AJAX call that will get the next 15 nba games and place them into a games div to easily manipulate. Next feature will be to manipulate them to a form so a user can pick a game, or will have to think of an other way to add user input.

Nba schedule feat

---

routes/api/index.js
server.js

added javascript logic to set up server in backend.

feat: set up server

---

app/public/css/style.css
app/public/home.html
app/public/index.html
app/public/login.html
app/public/signup.html

recovered stashed html files:
1.index.html
2.login.html
3.signup.html

recovered stashed html files

---

routes/html.js

edited html.js

---

.vscode/settings.json
README.md
app/public/css/style.css
app/public/dashboard.html
app/public/games.html
app/public/home.html
app/public/index.html
app/public/js/dashboard_layout.js
app/public/login.html
app/public/signup.html

-added updated dashboard.html
-edited footer in html files to be fixed to prevent overlapping content

dashboard.html & other minor .html edits

---

app/public/css/style.css
app/public/dashboard.html
app/public/games.html
app/public/home.html
app/public/index.html
app/public/login.html
app/public/signup.html
app/public/userdashboard.html

updated:
--games.html
--index.html
--style.css
first website prototype

updated games.html & index.html- first website prototype

---

public/dashboard.html
public/userdashboard.html
routes/api/html.js
routes/in.js
server.js

Fixes path issues when linking public CSS files on homepage and dashboard
Dashboard
Home

fix: Update stylesheet links to render pages properly client-side

---

db/schema.sql
models/bets.js

Add bet model with sequelize logic. Also updated schema. Doing this so the model can be referenced in the api routes

chore: create bet table in sequelize and update schema

---

config/index.js
models/bets.js
routes/api/bets.js

Fixed code in bets model js. Also, put in code for the bets controller js file. Lastly, uncommented out code in index.js in models as we will possibly need for sequelize CLI

chore: fix code in routes, models, and index

---

models/bets.js
models/users.js
routes/api/bets.js
routes/api/users.js

Added api routes so that within server side logic we will be able to display users and bets

chore: fix sequelize code in models and routes

---

config/config.json
models/bets.js
models/index.js
routes/api/bets.js
routes/api/users.js
routes/bets.js
routes/index.js
server.js

Can connect to mysql db by running server.js

feat: sequelize db operational

---

package.json
routes/bets.js
routes/users.js
server.js

Added route that lets you add users. Still have to fix route for bets.

feat: user api routes operational

---

models/bets.js

Bets routes working. Now we just have to alter client-side javascript so that teams and wagers can be added!

feat: bets api route working. can get and post

---

server.js
views/bid.handlebars
views/dashboard.handlebars
views/game.handlebars
views/home.handlebars
views/userResults.handlebars

edited .hbs files ad added userDisplay.hbs file
-currently needs to be debugged
-table not displaying with users and user's bets

updated hbs files, added userdisplay hbs

---

routes/bets.js
routes/users.js

Can search user and bet by id! Also, can delete user and bet by id

feat: now can delete users and bets by id, and search by id

---

config/config.json
config/index.js
models/bets.js
public/js/userdash.js
routes/users.js
server.js
views/layouts/main.handlebars
views/partials/script.handlebars
views/schedule.handlebars

Added a script that lets you add page level js and css making app more scalable and functional

feat: individual js and style can be applied per handlebar page

---

config/config.json
public/css/style.css
public/js/bidFunction.js
public/js/userFunction.js
server.js
views/bid.handlebars
views/home.handlebars
views/login.handlebars
views/partials/navbar.handlebars
views/partials/script.handlebars
views/signup.handlebars
views/user.handlebars

added bid & create user hbs files

User display

---

models/bets.js
public/css/userdash.css
views/partials/script.handlebars
views/schedule.handlebars

Added upcoming NBA games with AJAX call the the sportsdb api. Also, added foreign keys so that only users can add bets.

feat: add foreign key restraint and schedule page

---

public/css/userdash.css
public/js/previousgames.js
views/schedule.handlebars

have past and upcoming nba schedules. Also have scores

feat: add upcoming and past games

---

public/js/userdash.js

Scores of upcoming games get displayed as blank instead of null

style: null values get displayed as blank

---

views/user.handlebars

modified user/handlebars

---

public/js/index.js
views/home.handlebars
views/layouts/main.handlebars

Connected database to main handlebar

feat: database connect to homedash

---

.vscode/settings.json
config/config.json
public/css/style.css
public/js/newmain.js
public/js/newuser.js
public/js/previousgames.js
public/js/userdash.js
server.js
views/dash.handlebars
views/home.handlebars
views/layouts/main2.handlebars
views/login.handlebars
views/newbets.handlebars
views/newmain.handlebars
views/newusers.handlebars
views/partials/footer.handlebars
views/partials/navbar.handlebars
views/partials/navbar2.handlebars
views/schedule.handlebars
views/signup.handlebars
views/user.handlebars

final layout edit
- all hbs files & js files

final edits, still bugs

---

config/config.json
public/js/newmain.js
views/login.handlebars
views/newbets.handlebars
views/newusers.handlebars
views/signup.handlebars

modified hbs files

---

public/js/newmain.js
server.js
views/partials/navbar.handlebars

-updated main homepage to /newmain landing page
-updated navbar without /signup & /login 
-edited newmain.js => changed text to "was placed on" & commented out "edit function & buttons"

updated homepage to newmain, minor edits in newmain.js
